# Generated by Django 5.1.2 on 2024-11-02 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetHomeAPP', '0002_solicitudadopcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='disponible',
        ),
        migrations.AddField(
            model_name='animal',
            name='edad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.CharField(max_length=100),
        ),
    ]
