# Generated by Django 5.1.2 on 2024-11-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetHomeAPP', '0003_remove_animal_disponible_animal_edad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='usuario_default', max_length=100, unique=True),
        ),
    ]
