# Generated by Django 5.1.2 on 2024-11-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetHomeAPP', '0004_usuario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_cuenta',
            field=models.CharField(default='normal', max_length=10),
        ),
    ]
