# Generated by Django 5.1.2 on 2024-11-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetHomeAPP', '0005_usuario_tipo_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_cuenta',
            field=models.CharField(choices=[('normal', 'Normal'), ('admin', 'Administrador')], default='normal', max_length=10),
        ),
    ]
