# Generated by Django 5.1.2 on 2024-11-03 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetHomeAPP', '0010_animal_disponible_alter_animal_edad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudadopcion',
            old_name='fecha_creacion',
            new_name='fecha_solicitud',
        ),
        migrations.RemoveField(
            model_name='solicitudadopcion',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='solicitudadopcion',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='solicitudadopcion',
            name='telefono',
        ),
        migrations.AddField(
            model_name='animal',
            name='registrado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='animales_registrados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='animal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PetHomeAPP.animal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
