# Generated by Django 5.1.2 on 2024-11-03 04:43

import PetHomeAPP.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetHomeAPP', '0011_rename_fecha_creacion_solicitudadopcion_fecha_solicitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=10, validators=[PetHomeAPP.validator.validar_rut]),
        ),
    ]
