# Generated by Django 5.1.2 on 2024-11-03 05:46

import PetHomeAPP.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetHomeAPP', '0012_alter_usuario_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=10, unique=True, validators=[PetHomeAPP.validator.validar_rut]),
        ),
    ]
