# Generated by Django 5.1.2 on 2024-11-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetHomeAPP', '0013_alter_usuario_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudadopcion',
            name='correo',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='rut',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='telefono',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitudadopcion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10),
        ),
    ]
