# Generated by Django 5.1.2 on 2024-11-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetHomeAPP', '0014_solicitudadopcion_correo_solicitudadopcion_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudadopcion',
            name='animal_adoptado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='mensaje',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudadopcion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], max_length=20),
        ),
    ]
