# Generated by Django 5.1.2 on 2024-11-05 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetHomeAPP', '0015_solicitudadopcion_animal_adoptado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='adoptado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='solicitudadopcion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
    ]
